export { smartEnter } from './enter.func'
export { heading } from './heading.func'
export { toggleComment } from './comment.func'
export { insertCodeBlock } from './codeblock.func'
export { bracketOnNine } from './parentheses.func'
export { tabCompletion } from './autotab.extension'
export { dashRule } from './dash.input'
export { swapKeys } from './keystrokes.input'
export { sectionFold, toggleSectionFold, initialFoldsFacet, foldsFacet } from './fold'
export { executeNewlineIndent, executeNewlineDedent, executeCursorRight, executeNewline } from './qchord'
export { inoremap } from './inoremap'
