import { join, relative } from 'node:path'
import { writeFile } from 'node:fs/promises'
import { deriveRoute } from './slug'

export interface RouteInfo {
  file: string
  component: string
  slug: string
}

// Writes src/web-demo-runner.generated.tsx: real imports of every demo file
// keyed by slug, consumed by web-demo-runner.app.tsx.
export async function generateRoutes(root: string, files: string[]): Promise<RouteInfo[]> {
  const srcDir = join(root, 'src')
  const infos: RouteInfo[] = files.map((file) => {
    const { component, slug } = deriveRoute(file)
    return { file, component, slug }
  })

  const imports = infos
    .map((info, i) => `import Demo${i} from '${importPath(srcDir, info.file)}'`)
    .join('\n')

  const entries = infos
    .map((info, i) => `  { slug: '${info.slug}', component: '${info.component}', Component: Demo${i} },`)
    .join('\n')

  const out = `// web-demo-runner.generated.tsx
// AUTO-GENERATED by @paladin/internal-commands/webrun — do not edit.
${imports}

export const routes = [
${entries}
]
`
  await writeFile(join(srcDir, 'web-demo-runner.generated.tsx'), out)
  return infos
}

function importPath(srcDir: string, file: string) {
  let rel = relative(srcDir, file).replace(/\\/g, '/')
  if (!rel.startsWith('.')) rel = `./${rel}`
  return rel
}
