import type { ExportedFn } from "../types"
import { pascal } from "../paths"

// emits a thin wrapper that hands endpoint metadata to the runtime DemoApplet
export function generateDemoApplet(
  featureName: string,
  fns: ExportedFn[],
): string {
  const componentName = `${pascal(featureName)}DemoApplet`
  const endpoints = fns.map((fn) => ({
    name: fn.name,
    method: fn.method,
    route: fn.route,
    params: fn.params.map((p) => ({
      name: p.name,
      type: p.tsType === "enum" ? "enum" : p.tsType,
      ...(p.literalUnion ? { options: p.literalUnion } : {}),
    })),
  }))

  const endpointsJson = JSON.stringify(endpoints, null, 2)

  return `// auto-generated by wire()
import { DemoApplet, type Endpoint } from '@/components/applets/_shared/DemoApplet'

const endpoints: Endpoint[] = ${endpointsJson}

export function ${componentName}() {
  return <DemoApplet feature=${JSON.stringify(featureName)} endpoints={endpoints} />
}

export default ${componentName}
`
}
