import { useCallback, useEffect, useMemo, useRef, useState } from "react"
import { createRoot } from "react-dom/client"
// @ts-expect-error generated by the storylite vite plugin
import entries from "virtual:storylite/stories"
import type { Report, Result } from "../types"
import { loadGroups, type Entry, type Group, type Story } from "./model"
import { plannedSteps, run } from "./runner"
import "./storylite.css"

declare global {
  interface Window {
    __storylite?: Report
  }
}

/** `?headless` is the CLI's way in: run everything, show nothing */
const headless = new URLSearchParams(location.search).has("headless")

const readHash = () => decodeURIComponent(location.hash.slice(1))

/**
 * one story runs at a time. plays drive real focus, selection and timers, so two at once
 * (the background run-all and the story you just clicked) would trample each other.
 */
let queue: Promise<unknown> = Promise.resolve()
const exclusive = <T,>(task: () => Promise<T>): Promise<T> => {
  const next = queue.then(task, task)
  queue = next.catch(() => {})
  return next
}

/** a click on the sidebar must not take focus from the story: a step typing into a palette would type into the button */
const keepFocus = (e: { preventDefault(): void }) => e.preventDefault()

const later = (ms: number) => new Promise<void>((resolve) => setTimeout(resolve, ms))

/** resolves once the tab is in view: a hidden one runs its timers about once a second, which stalls a step */
const visible = () =>
  document.visibilityState === "visible" || headless
    ? Promise.resolve()
    : new Promise<void>((resolve) => {
        const on = () => document.visibilityState === "visible" && (document.removeEventListener("visibilitychange", on), resolve())
        document.addEventListener("visibilitychange", on)
      })

const idle = (s: Story): Result => ({ id: s.id, file: s.file, title: s.title, name: s.name, status: "idle", play: !!s.def.play || !!s.def.steps?.length, ms: 0, steps: plannedSteps(s) })

function App({ groups }: { groups: Group[] }) {
  const stories = useMemo(() => groups.flatMap((g) => g.stories), [groups])
  const [results, setResults] = useState<Record<string, Result>>(() => Object.fromEntries(stories.map((s) => [s.id, idle(s)])))
  const [selected, setSelected] = useState(readHash)
  const [finished, setFinished] = useState(false)
  // picking a story only renders it. `drive` is the play button: its play function and steps run, paced so you can watch
  const [go, setGo] = useState({ n: 0, drive: false, id: "" })
  // the live canvas sits out the background run: two copies of a story would both answer a global hotkey
  const [busy, setBusy] = useState(false)
  const stage = useRef<HTMLDivElement>(null)
  const canvas = useRef<HTMLDivElement>(null)

  const record = useCallback((r: Result) => setResults((all) => ({ ...all, [r.id]: r })), [])

  useEffect(() => {
    const sync = () => setSelected(readHash())
    addEventListener("hashchange", sync)
    return () => removeEventListener("hashchange", sync)
  }, [])

  // the CLI reads this once `done`; it is the same data the sidebar shows
  useEffect(() => {
    const errors = groups.filter((g) => g.error).map((g) => ({ file: g.file, error: g.error! }))
    window.__storylite = { done: finished, results: Object.values(results), errors }
  }, [results, finished, groups])

  // every story runs once in an offscreen stage, so the sidebar shows pass/fail without clicking through
  const runAll = useCallback(async () => {
    setFinished(false)
    setBusy(true)
    // a story that fails because the page was still settling (vite reloading for a late dependency, fonts, a
    // tab nobody is looking at running its timers once a second) is not a failing story. so: let the page
    // load, only run while it is visible, and give a failure one more go before calling it one
    if (!headless) await Promise.all([later(1_000), visible()])
    const once = (story: Story) =>
      exclusive(async () => {
        const out = await run(story, stage.current!, record)
        out.dispose()
        return out.result
      })
    for (const story of stories) {
      await visible()
      let result = await once(story)
      if (result.status === "fail") {
        await later(500)
        const again = await once(story)
        result = again.status === "pass" ? { ...again, retried: true } : again
      }
      record(result)
    }
    setBusy(false)
    setFinished(true)
  }, [stories, record])

  useEffect(() => {
    void runAll()
  }, [runAll])

  // a run-all opens every story's dialogs in turn; they are there for the steps, not to be looked at
  useEffect(() => {
    document.body.classList.toggle("sl-running", busy)
  }, [busy])

  const current = headless ? undefined : (stories.find((s) => s.id === selected) ?? stories[0])

  // the selected story, live in the visible canvas, play and all. torn down when you pick another
  useEffect(() => {
    if (!current || !canvas.current || busy) return
    let dead = false
    let dispose = () => {}
    const el = canvas.current
    // play belongs to the story it was pressed on; picking another only renders it
    const drive = go.drive && go.id === current.id
    void exclusive(async () => {
      if (dead) return
      const out = await run(current, el, (r) => !dead && drive && record(r), { slow: drive, drive })
      dispose = out.dispose
      if (dead) out.dispose()
      // a render that only looked is not a verdict, unless it broke
      else if (drive || out.result.status === "fail") record(out.result)
    })
    return () => {
      dead = true
      dispose()
    }
  }, [current, go, busy, record])

  const counts = { pass: 0, fail: 0, other: 0 }
  for (const r of Object.values(results)) counts[r.status === "pass" ? "pass" : r.status === "fail" ? "fail" : "other"]++
  const shown = current ? results[current.id] : undefined

  return (
    <div className="sl-app">
      <aside className="sl-side" data-sl-chrome>
        <div className="sl-head">
          <b>storylite</b>
          <button className="sl-btn" onMouseDown={keepFocus} onClick={() => void runAll()}>
            run all
          </button>
        </div>
        <div className="sl-summary" data-summary>
          <span>✓ {counts.pass}</span>
          <span>✗ {counts.fail}</span>
          <span>{busy ? "running…" : finished ? "done" : "idle"}</span>
        </div>
        <nav className="sl-tree">
          {groups.length === 0 && <p className="sl-muted">no .stories. files found</p>}
          {groups.map((g) => (
            <div key={g.file}>
              <div className="sl-group" title={g.file}>
                {g.title}
              </div>
              {g.error && <pre className="sl-error">{g.error}</pre>}
              {g.stories.map((s) => (
                <button key={s.id} className="sl-row" data-story={s.id} aria-current={s.id === current?.id} onMouseDown={keepFocus} onClick={() => (location.hash = encodeURIComponent(s.id))}>
                  <i className="sl-dot" data-status={results[s.id]?.status} />
                  {s.name}
                </button>
              ))}
            </div>
          ))}
        </nav>
      </aside>

      <main className="sl-main">
        <div className="sl-bar" data-sl-chrome>
          <strong>{current ? `${current.title} / ${current.name}` : ""}</strong>
          <span>{current?.file}</span>
          {current && (
            <>
              {current.def.steps?.length ? (
                <button className="sl-btn sl-play" data-play onMouseDown={keepFocus} disabled={busy} title="run the steps slowly, to watch them" onClick={() => setGo((g) => ({ n: g.n + 1, drive: true, id: current.id }))}>
                  ▶ play
                </button>
              ) : null}
              <button className="sl-btn" disabled={busy} onClick={() => setGo((g) => ({ n: g.n + 1, drive: false, id: current.id }))}>
                re-run
              </button>
            </>
          )}
        </div>
        <div className="sl-canvas" ref={canvas} data-canvas />
        {busy && <p className="sl-muted sl-busy">running every story…</p>}
        <div className="sl-panel" data-panel data-sl-chrome>
          {shown ? <Panel result={shown} /> : <span className="sl-muted">select a story</span>}
        </div>
      </main>

      <div className="sl-stage" ref={stage}/>
    </div>
  )
}

function Panel({ result }: { result: Result }) {
  const label = result.status === "pass" ? (result.play ? "play passed" : "rendered") : result.status === "fail" ? "failed" : result.status === "idle" ? "not run" + (result.steps.length ? " · ▶ play runs the steps" : "") : result.status
  return (
    <>
      <h3 data-status={result.status}>
        {label}
        {result.status !== "idle" && result.status !== "running" ? ` · ${result.ms}ms` : ""}
      </h3>
      {result.steps.map((s, i) => (
        <div key={i} className="sl-step" data-status={s.status}>
          <span>{s.status === "pass" ? "✓" : s.status === "fail" ? "✗" : s.status === "running" ? "▶" : "·"}</span>
          <span>
            {s.name}
            {s.desc && <small className="sl-desc">{s.desc}</small>}
            {s.error && <small className="sl-desc sl-fail">{s.error}</small>}
          </span>
        </div>
      ))}
      {result.error && <pre className="sl-error">{result.error}</pre>}
    </>
  )
}

async function main() {
  const groups = await loadGroups(entries as Entry[])
  createRoot(document.getElementById("root")!).render(
    // no StrictMode: its doubled effects would run every play twice
    <App groups={groups} />,
  )
}

void main()
