import { describe, expect, test } from "bun:test"
import { extractHeader } from "./extract-header"

describe("extractHeader", () => {
  test("finds the first valid header after multiple leading comments", () => {
    const content = [
      "// generated by claude",
      "// TODO: review this file",
      "// @acme/pkg/src/file.ts -- append",
      "export const x = 1",
    ].join("\n")

    expect(extractHeader(content)).toEqual({
      rawPath: "@acme/pkg/src/file.ts",
      action: "append",
    })
  })

  test("parses delete action instead of skipping it", () => {
    expect(extractHeader("// @acme/pkg/src/file.ts -- delete")).toEqual({
      rawPath: "@acme/pkg/src/file.ts",
      action: "delete",
    })
  })

  test("skips deprecated headers", () => {
    expect(extractHeader("// @acme/pkg/src/file.ts deprecated")).toBeNull()
    expect(extractHeader("// @acme/pkg/src/file.ts -- deprecate")).toBeNull()
  })
})
