import {join} from 'node:path'

const PKG = join(import.meta.dir, '..')
const GLOBALS = join(PKG, 'src', 'styles', 'globals.css')
const SOURCE = join(PKG, 'src', 'styles', 'source.css')

const TAILWIND_IMPORT_RE = /^\s*@import\s+['"]tailwindcss['"][^;]*;\s*$/

const globals = await Bun.file(GLOBALS).text()
const stripped = globals
  .split('\n')
  .filter(line => !TAILWIND_IMPORT_RE.test(line))
  .join('\n')

const header = [
  '/* generated by scripts/build-css.ts - do not edit */',
  '/* app tailwind entry: @import "@paladin/shadcn/source.css"; */',
  '',
  '',
].join('\n')

await Bun.write(SOURCE, header + stripped)

console.log('css: src/styles/source.css')
