// @paladin/shadcn/scripts/build-css.ts
//
// compiles the package's own tailwind output to dist/styles.css, which the
// barrel imports - so a consumer gets styles just by importing a component.
//
// also emits src/styles/source.css: the same graph minus the tailwind import,
// for apps that would rather compile this package with their own build.

import {join} from 'node:path'

const PKG = join(import.meta.dir, '..')
const GLOBALS = join(PKG, 'src', 'styles', 'globals.css')
const SOURCE = join(PKG, 'src', 'styles', 'source.css')

const TAILWIND_IMPORT_RE = /^\s*@import\s+['"]tailwindcss['"][^;]*;\s*$/

const globals = await Bun.file(GLOBALS).text()
const stripped = globals
  .split('\n')
  .filter(line => !TAILWIND_IMPORT_RE.test(line))
  .join('\n')

const header = [
  '/* generated by scripts/build-css.ts - do not edit */',
  '/* app tailwind entry: @import "@paladin/shadcn/source.css"; */',
  '',
  '',
].join('\n')

await Bun.write(SOURCE, header + stripped)

const proc = Bun.spawn(
  ['bunx', '--bun', '@tailwindcss/cli', '-i', './src/styles/globals.css', '-o', './dist/styles.css', '--minify'],
  {cwd: PKG, stdout: 'inherit', stderr: 'inherit'},
)

const code = await proc.exited
if (code !== 0) process.exit(code)

const size = Bun.file(join(PKG, 'dist', 'styles.css')).size
console.log('css: dist/styles.css (' + Math.round(size / 1024) + 'kb) + src/styles/source.css')
