// @paladin/shadcn/scripts/generate-barrel.ts
//
// scans src/ and regenerates src/index.ts so consumers can do
//   import {Button, toast, cn} from '@paladin/shadcn'
//
// re-run after every shadcn add: bun run sync

import {Glob} from 'bun'
import {join} from 'node:path'

const SRC = join(import.meta.dir, '..', 'src')

const PATTERNS = ['components/ui/*.tsx', 'components/*.tsx', 'lib/*.ts', 'hooks/*.ts', 'hooks/*.tsx']

// [module, values, types] appended verbatim after the scanned files
const EXTRA: Array<[string, string[], string[]]> = [
  ['clsx', ['clsx'], ['ClassValue']],
  ['tailwind-merge', ['twMerge'], []],
  ['class-variance-authority', ['cva'], ['VariantProps']],
  ['sonner', ['toast'], []],
]

const VALUE_RE = /export\s+(?:async\s+)?(?:function|const|let|var|class)\s+([A-Za-z0-9_$]+)/g
const TYPE_DECL_RE = /export\s+(?:type|interface)\s+([A-Za-z0-9_$]+)/g
const TYPE_BLOCK_RE = /export\s+type\s*\{([^}]*)\}/g
const BLOCK_RE = /export\s*\{([^}]*)\}/g
const IDENT_RE = /^[A-Za-z0-9_$]+$/

const parseBlock = (body: string) => {
  const values: string[] = []
  const types: string[] = []
  for (const raw of body.split(',')) {
    const part = raw.trim()
    if (!part || part === 'default') continue
    const isType = part.startsWith('type ')
    const cleaned = isType ? part.slice(5).trim() : part
    const name = cleaned.includes(' as ') ? cleaned.split(' as ')[1].trim() : cleaned
    if (!IDENT_RE.test(name) || name === 'default') continue
    if (isType) types.push(name)
    else values.push(name)
  }
  return {values, types}
}

const files = new Set<string>()
for (const pattern of PATTERNS) {
  for await (const rel of new Glob(pattern).scan({cwd: SRC, onlyFiles: true})) {
    const norm = rel.split('\\').join('/')
    if (norm === 'index.ts') continue
    files.add(norm)
  }
}

const seen = new Set<string>()
const skipped: string[] = []
const lines: string[] = []

const take = (names: string[], origin: string) => {
  const out: string[] = []
  for (const name of new Set(names)) {
    if (seen.has(name)) {
      skipped.push(name + ' from ' + origin)
      continue
    }
    seen.add(name)
    out.push(name)
  }
  return out.sort()
}

const emit = (mod: string, values: string[], types: string[]) => {
  const v = take(values, mod)
  const t = take(types, mod)
  if (v.length) lines.push('export {' + v.join(', ') + "} from '" + mod + "'")
  if (t.length) lines.push('export type {' + t.join(', ') + "} from '" + mod + "'")
}

for (const rel of [...files].sort()) {
  const text = await Bun.file(join(SRC, rel)).text()
  const values: string[] = []
  const types: string[] = []

  for (const m of text.matchAll(VALUE_RE)) values.push(m[1])
  for (const m of text.matchAll(TYPE_DECL_RE)) types.push(m[1])
  for (const m of text.matchAll(TYPE_BLOCK_RE)) {
    const parsed = parseBlock(m[1])
    types.push(...parsed.values, ...parsed.types)
  }
  for (const m of text.matchAll(BLOCK_RE)) {
    const parsed = parseBlock(m[1])
    values.push(...parsed.values)
    types.push(...parsed.types)
  }

  const mod = './' + rel.replace(/\.tsx?$/, '')
  emit(mod, values, types)
}

for (const [mod, values, types] of EXTRA) emit(mod, values, types)

const header = [
  '// @paladin/shadcn/src/index.ts',
  '// generated by scripts/generate-barrel.ts - do not edit by hand',
  '',
]

await Bun.write(join(SRC, 'index.ts'), header.concat(lines).join('\n') + '\n')

console.log('barrel: ' + seen.size + ' exports from ' + files.size + ' files')
if (skipped.length) console.log('barrel: name collisions skipped -> ' + skipped.join(', '))
