import type { ScopeTable } from "../keys/extend"

const nav = {
  "<Up>": "modal.up",
  "<Down>": "modal.down",
  "<Left>": "modal.left",
  "<Right>": "modal.right",
}

export const MODAL_BINDINGS: ScopeTable = {
  normal: {
    "<A-l>": "component.loader",
    "<A-S-l>": "component.loader.sibling",
    "<A-i>": "icon.picker",
    "?": "help.open",
    "<mod-/>": "help.open",
  },
  modal: {
    ...nav,
    "<Space>": "modal.cycle",
    "<S-Space>": "modal.cycle.back",
    "<A-Up>": "modal.nudge.up",
    "<A-Down>": "modal.nudge.down",
    "<A-S-Up>": "modal.nudge.up.big",
    "<A-S-Down>": "modal.nudge.down.big",
    "<Enter>": "modal.edit",
    i: "modal.input",
    "/": "modal.filter",
    x: "modal.reset",
    "<Tab>": "modal.scope",
    "<Esc>": "modal.close",
    "?": "modal.close",
  },
  "modal-text": {
    "<Up>": "modal.up",
    "<Down>": "modal.down",
    "<Left>": "modal.left",
    "<Right>": "modal.right",
    "<A-Up>": "modal.nudge.up",
    "<A-Down>": "modal.nudge.down",
    "<A-S-Up>": "modal.nudge.up.big",
    "<A-S-Down>": "modal.nudge.down.big",
    "<Enter>": "modal.text.commit",
    "<Esc>": "modal.text.cancel",
    "<BS>": "modal.text.backspace",
    "<S-BS>": "modal.text.deleteWord",
  },
}

export const MODAL_COMMANDS = [
  { id: "component.loader", title: "Component loader", group: "normal", description: "Insert a saved component as a child of the focused node" },
  { id: "component.loader.sibling", title: "Component loader (sibling)", group: "normal", description: "Insert a saved component after the focused node" },
  { id: "icon.picker", title: "Icon picker", group: "normal", description: "Insert an icon" },
  { id: "help.open", title: "Help palette", group: "normal", description: "Every command with its current key" },
  { id: "modal.up", title: "Previous row / item", group: "modal" },
  { id: "modal.down", title: "Next row / item", group: "modal" },
  { id: "modal.left", title: "Previous section", group: "modal" },
  { id: "modal.right", title: "Next section", group: "modal" },
  { id: "modal.cycle", title: "Toggle / cycle", group: "modal" },
  { id: "modal.cycle.back", title: "Cycle backward", group: "modal" },
  { id: "modal.nudge.up", title: "Nudge +1", group: "modal" },
  { id: "modal.nudge.down", title: "Nudge −1", group: "modal" },
  { id: "modal.nudge.up.big", title: "Nudge +10", group: "modal" },
  { id: "modal.nudge.down.big", title: "Nudge −10", group: "modal" },
  { id: "modal.edit", title: "Edit row inline", group: "modal" },
  { id: "modal.input", title: "Input mode for the section", group: "modal", description: "type property tokens, e.g. w20p h100p on Rect" },
  { id: "modal.filter", title: "Filter rows", group: "modal" },
  { id: "modal.reset", title: "Reset row", group: "modal" },
  { id: "modal.scope", title: "Global / this artboard", group: "modal", description: "node defaults can override per artboard" },
  { id: "modal.close", title: "Close", group: "modal" },
  { id: "modal.text.commit", title: "Commit", group: "modal-text" },
  { id: "modal.text.cancel", title: "Cancel", group: "modal-text" },
  { id: "modal.text.backspace", title: "Delete character", group: "modal-text" },
  { id: "modal.text.deleteWord", title: "Delete word", group: "modal-text" },
]
