export { inputRules, undoInputRule } from './engine'
export { applyRules, inputRuleTransaction, inputRuleEvent, splitCursor } from './apply'
export { resolveConfig } from './config'
export type { InputRulesConfig, ResolvedConfig } from './config'
export { abbrevs } from './abbrevs'
export type { AbbrevOptions } from './abbrevs'
export { wraps, matchWrap } from './wraps'
export { notIn, onlyIn, atLineEnd } from './guards'
export type { InputRule, Insert, RuleContext, RuleResult, WrapSpec, ResolvedWrap } from './types'

export { punctuationSwaps, punctuationRules, punctuationAbbrevSource } from './presets/punctuation'
export { markdownRules, dashRules, headingRules, HORIZONTAL_RULE } from './presets/markdown'
export { bracketWraps, bracketRules } from './presets/brackets'
